-- 既存のテーブルを削除（存在する場合）
DROP TABLE IF EXISTS public.messages;
DROP TABLE IF EXISTS public.replies;

-- メインメッセージのテーブルを作成
CREATE TABLE public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- レス用のテーブルを作成
CREATE TABLE public.replies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint REFERENCES public.messages(id) ON DELETE CASCADE,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- アクセス権限を設定
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.replies ENABLE ROW LEVEL SECURITY;

-- メッセージテーブルのポリシーを設定
CREATE POLICY "Enable read access for all users" ON public.messages 
    FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.messages 
    FOR INSERT WITH CHECK (true);

-- レステーブルのポリシーを設定
CREATE POLICY "Enable read access for all users" ON public.replies 
    FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.replies 
    FOR INSERT WITH CHECK (true); 