-- 既存のテーブルを削除（存在する場合）
DROP TABLE IF EXISTS public.messages;

-- テーブルを作成
CREATE TABLE public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- アクセス権限を設定
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 読み取りと書き込みのポリシーを設定
CREATE POLICY "Enable read access for all users" ON public.messages 
    FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.messages 
    FOR INSERT WITH CHECK (true); 